### ISSUE TITLE
 Code confusion in L1optimal method

### ISSUE THREAD

**Issue by zhaoxin111** [ishank-juneja/L1-optimal-paths-Stabilization#2]
First of all, thank you very much for sharing such excellent work. I tried the L1 method and the result was very good. When I analyzed the code in depth, I found that I could not understand the design of the transform_product method in L1optimal_lpp.py。
transform_product method actually need to multiply two matrices， but why out the result by specific manaer?
![未命名1611282922](https://user-images.githubusercontent.com/9295202/105438254-938c5300-5c9d-11eb-936a-9ca9b5c22826.png)

**Comment by ishank-juneja** [comment]
Thank you for your interest in our project.
The reason for making the product into a flattened vector is related to the formulation of the linear programming optimization problem using the PuLP library.
Later in the file `L1_optimal_lpp.py` if you see the `stabilize()` function you will notice that this particular flattened structure has been useful in the lines 122-129 to add constraints using a single `for` loop. 

The particular structure is consistent with the choice taken in the CVPR research paper and since it had to be done multiple times I made a function out of it.

**Comment by zhaoxin111** [comment]
> Thank you for your interest in our project.
> The reason for making the product into a flattened vector is related to the formulation of the linear programming optimization problem using the PuLP library.
> Later in the file `L1_optimal_lpp.py` if you see the `stabilize()` function you will notice that this particular flattened structure has been useful in the lines 122-129 to add constraints using a single `for` loop.
> 
> The particular structure is consistent with the choice taken in the CVPR research paper and since it had to be done multiple times I made a function out of it.

Thank you for your quick reply, I have understood the purpose of this. Note that the pulp is written in loops. I don't know if this block can be optimized into a matrix expression. Maybe this can optimize the optimization speed of LP. However, from the results, the main time-consuming is the extraction of the F matrix.

**Comment by ishank-juneja** [comment]
Yes, initially my preference was to keep the computations in matrix form. In a language like MATLAB this is quite easy using their symbolic library however for the Python solution I couldn't find any such library that would also be compatible with PuLP. 

PuLP only allows adding constraints in a vectored form if they are 1 dimensional. There was no direct way to add a "Matrix of constraints" in one go.

**Comment by zhaoxin111** [comment]
> Yes, initially my preference was to keep the computations in matrix form. In a language like MATLAB this is quite easy using their symbolic library however for the Python solution I couldn't find any such library that would also be compatible with PuLP.
> 
> PuLP only allows adding constraints in a vectored form if they are 1 dimensional. There was no direct way to add a "Matrix of constraints" in one go.

Thank you for your reply, I will continue to pay attention to your nice project！
